import Head from "next/head";
function HeaderTitle({ title }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/takealot-logo.png" />
      </Head>
    </div>
  );
}

export default HeaderTitle;
