import Head from "next/head";
function HeaderTitle() {
  return (
    <div>
      <Head>
        <title>Takealot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/takealot-logo.png" />
      </Head>
    </div>
  );
}

export default HeaderTitle;
