import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Takealot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/takealot-logo.png" />
      </Head>
      <h1>hello</h1>
    </div>
  );
}
